# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.
# Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_1:
    has_position_limits: true
    min_position: -1.570796   # -90 deg (servo 0-180 with calibrated offset)
    max_position: 1.570796   # 90 deg
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 3.0
  joint_2:
    has_position_limits: true
    min_position: -0.785398   # -45 deg (servo 0-180 with calibrated offset)
    max_position: 2.356194   # 135 deg
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 3.0
  joint_3:
    has_position_limits: true
    min_position: -2.007129   # -115 deg (servo 0-180 with calibrated offset)
    max_position: 1.134464   # 65 deg
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 3.0
  joint_4:
    has_position_limits: true
    min_position: 0.000000   # 0 deg (servo 0-180 with calibrated offset)
    max_position: 3.141593   # 180 deg
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 3.0
  joint_5:
    has_position_limits: true
    min_position: -3.490659   # -200 deg (servo 0-180 with calibrated offset)
    max_position: -0.349066   # -20 deg
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 3.0
  joint_6:
    has_position_limits: true
    min_position: -1.570796   # -90 deg (servo 0-180 with calibrated offset)
    max_position: 1.570796   # 90 deg
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 3.0
